""" A module to contain helper functions offering utility functionality for
    the Harmony GDAL Adapter Service.

"""
from glob import glob
from os import rename
from os.path import dirname, exists, join as path_join, splitext
from typing import List
import re

from harmony.util import generate_output_filename

known_file_types = {'.nc': 'nc', '.nc4': 'nc', '.tif': 'tif', '.tiff': 'tif',
                    '.zip': 'zip'}

mime_to_gdal = {'image/tiff': 'GTiff',
                'image/png': 'PNG',
                'image/gif': 'GIF',
                'application/x-netcdf4': 'NETCDF',
                'application/x-zarr': 'zarr'}

mime_to_extension = {'image/tiff': 'tif',
                     'image/png': 'png',
                     'image/gif': 'gif',
                     'application/x-netcdf4': 'nc',
                     'application/x-zarr': 'nc'}

process_flags = {'subset': False,
                 'maskband': False}

resampling_methods = ['nearest', 'bilinear', 'cubic', 'cubicspline', 'lanczos',
                      'average', 'rms', 'mode']


def get_file_type(input_file_name: str) -> str:
    """ Determine the input file type according to its extension. If the
        format is not recognised the extension is returned so it can be
        provided in a raised exception and the message returned to the
        end-user.

    """
    if input_file_name is None or not exists(input_file_name):
        file_type = None
    else:
        file_extension = splitext(input_file_name)[-1]
        file_type = known_file_types.get(file_extension, file_extension)

    return file_type


def get_version() -> str:
    """ Retrieve the version of the HGA Docker image from version.txt. """
    with open('version.txt', mode='r', encoding='utf-8') as file_version:
        version = ','.join(file_version.readlines())

    return version


def get_files_from_unzipfiles(extract_dir: str, filetype: str,
                              variables=None) -> List[str]:
    """
    inputs: extract_dir which include geotiff files, filetype is
    either 'tif' or 'nc', variables is the list of variable names.
    return: filelist for variables.
    """
    tmpexp = path_join(extract_dir, f'*.{filetype}')
    filelist = sorted(glob(tmpexp))
    ch_filelist = []
    if filelist:
        if variables:
            if 'Band' not in variables[0]:
                for variable in variables:
                    variable_tmp = variable.replace('-', '_')
                    variable_raw =fr'{variable_tmp}'
                    for filename in filelist:
                        if re.search(variable_raw, filename.replace('-', '_')):
                            ch_filelist.append(filename)
                            break
            else:
                ch_filelist = filelist
        else:
            ch_filelist = filelist
    return ch_filelist


def rename_file(input_filename: str, href: str) -> str:
    """ Rename a given file to a name generated by the harmony-service-lib. """
    output_filename = path_join(dirname(input_filename),
                                generate_output_filename(href))
    rename(input_filename, output_filename)
    return output_filename
