name: Publish Harmony GDAL Adapter Docker image

on:
  push:
    branches: [ main ]
    paths: version.txt

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml

  build_and_publish_image:
    needs: run_tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - name: Checkout harmony-gdal-adapter repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract semantic version number
        run: echo "semantic_version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Extract release version notes
        run: |
          version_release_notes=$(./bin/extract-release-notes.sh)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "${version_release_notes}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Log-in to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tags to the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.semantic_version }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/service.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.RELEASE_NOTES }}
          commit: main
          name: Version ${{ env.semantic_version }}
          tag: ${{ env.semantic_version }}
